---
apiVersion: v1
kind: Secret
metadata:
  name: repo-a
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  project: proj-a
  name: repo-a
  url: git@github.com:hello/private/repo.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    invalid
    -----END OPENSSH PRIVATE KEY-----
